title: revtools
author: Martin Westgate
email: martinjwestgate@gmail.com
description: An R package for screening in evidence synthesis projects
theme: minima
show_excerpts: false
google_analytics: UA-121833450-2
minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: westgatecology
    github:  mjwestgate
plugins:
 - jekyll-feed
 - jekyll-seo-tag
header_pages:
- docs/introduction.md
- docs/import.md
- docs/deduplication.md
- docs/screening.md