title: revtools
email: martinjwestgate@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An R package for screening in evidence synthesis projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: true
google_analytics: UA-121833450-2
header_pages:
- docs/introduction.md
- docs/import.md
- docs/deduplication.md
- docs/screening.md
minima:
  date_format: "%Y-%m-%d"
social_links:
  twitter: westgatecology
  github:  mjwestgate