title: revtools
author: Martin Westgate
description: Tools for Evidence Synthesis in R
theme: minima
github_username: mjwestgate
twitter_username: westgatecology
email: martinjwestgate@gmail.com
google_analytics: true
exclude: ["README.md"]
google_analytics: UA-121833450-2
header_pages:
- docs/Import.md
- docs/Deduplication.md
- docs/Screening.md